<?php  foreach ($products as $product) { ?>
<div class="default-review">
	<div class="row">
		<div class="col-sm-2"><a href="<?php echo $this->url('product', array('action' => 'product', 'id'=>$product->product_id)); ?>" class="">
			<img src="<?php $path = explode("/",$product->product_image,4);

			echo $this->basePath().'/'.$path[3]; ?>" id="image_male" class="img-responsive"></a>
		</div>
		<div class="col-sm-10">
			<h3 class="title"><?php echo $product->product_name; ?></h3>
			<p class="text-muted"><span class="glyphicon glyphicon-lock"></span> Available Exclusively for Premium Members</p>
			<p><?php echo $product->product_desc; ?><p>
			<p class="text-muted">$<?php echo $product->price; ?></a></p>
		</div>
	</div>
<hr>
</div>
<?php } ?>