<?php 
if(isset($product) && !empty($product)) :
	$path = explode("/",$product->product_image,4);  
?>

<div class="default-review col-sm-12">
	<div class="col-sm-5">
		<img src="<?php echo $this->basePath().'/'.$path[3]; ?>" id="image_male" class="img-responsive">
	</div>

	<div class="col-sm-4" style="float: right;">


<?php 
	$openFormGroup = '<div class="form-group form-group-sm col-sm-12">';
	$closeFormGroup = '</div>';
	$startPrice = $product->price * 1;
	
	$form->setAttributes(array(
	    'action' => $this->url('product', array('action' => 'product', 'id' =>$product->product_id)),
	    'class'  => 'form-horizontal'
		));
	$form->prepare();
	
?>

<?php 
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('product_id')->setValue($product->product_id));
	echo "<input type='hidden' id='original_weight' value='".$product->weight."'>";
	echo $this->formHidden($form->get('weight')->setValue($product->weight)->setAttributes(array('id' => 'weight')));

	echo $openFormGroup;
	echo "	<label class='control-label col-sm-6'>Product Name:</label>&nbsp;
			<label class='control-label'>" .$product->product_name."</label>";
	echo $this->formRow($form->get('product_name')->setAttributes(array('class' => 'form-control'))->setValue($product->product_name));
	echo $closeFormGroup;

	echo $openFormGroup;
	echo "	<label class='control-label col-sm-6'>Product Description:</label>&nbsp;
			<span>" .$product->product_desc."</span>";
	echo $this->formRow($form->get('product_desc')->setValue($product->product_desc));
	echo $closeFormGroup;

	echo $openFormGroup;
	echo "	<label class='control-label col-sm-6'>Unit Price:</label>&nbsp;
			<label class='control-label'>" .$product->price."</label>";
	echo $this->formRow($form->get('unit_price')->setValue($product->price)->setAttributes(array('id' => 'unit_price')));
	echo $closeFormGroup;

	echo $openFormGroup;
	echo "<label class='control-label col-sm-6'>Quantity:</label>&nbsp;<div class='col-sm-4'> ";
	echo "<input type='hidden' id='total_qty' value='".$product->stock_qty."'>";
	if($product->stock_qty=='')
	echo $this->formRow($form->get('qty')->setAttributes(array('id' => 'qty', 'class' => 'form-control','disabled' => 'disabled')));
	else
	echo $this->formRow($form->get('qty')->setAttributes(array('id' => 'qty', 'class' => 'form-control'))->setValue(1));
	
	echo '</div>'.$closeFormGroup;

	echo $openFormGroup;
	if($product->stock_qty=='')
	echo "<label class='control-label col-sm-6'>Price:</label>&nbsp; <label class='control-label' id='price_html' style='color:red'>Out of stock</label>";
	else
	echo "<label class='control-label col-sm-6'>Price:</label>&nbsp; <label class='control-label' id='price_html'>$".number_format($startPrice,2)."</label>";
	echo $this->formRow($form->get('price')->setAttributes(array('id' => 'price'))->setValue($startPrice));
	echo $closeFormGroup;
	if($product->stock_qty=='')
	echo $this->formSubmit($form->get('submit')->setAttributes(array('class' => 'btn btn-success pull-right','disabled' => 'disabled')));	
	else
	echo $this->formSubmit($form->get('submit')->setAttributes(array('class' => 'btn btn-success pull-right')));
	echo $this->form()->closeTag();
 ?>
	</div>
</div>

<?php endif; ?>