<div class="row-fluid top30 pagetitle">
  
	<div class="container">

		<div class="row">
		 	 <div class="col-md-12"><h1>Training</h1></div>		  
		</div>
	</div>
  
</div>
<div class="container">
	<div class="row">
		<div class="col-md-3">
		  	<h4 class="">Search</h4>
			<div class="input-group">
			    <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
			    <div class="input-group-btn">
			      	<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>
			      	</button>
			    </div>
			</div>
		  	<button type="button" class="btn btn-default btn-sm btn-block hidden-lg hidden-md" data-toggle="collapse" data-target="#demo">Refine your search <span class="caret"></span></button>
		  
			<div id="demo" class="collapse in">
			<hr>
				<div class="list-group list-group">
					<h4 class="">Products Category</h4>
					
					<a href="#" class="list-group-item"><span class="badge">14</span> Active item <span class="label label-primary">New</span></a>
					<a href="#" class="list-group-item"><span class="badge">3</span> Second item</a>	
					<a href="#" class="list-group-item"><span class="badge">25</span> Third item</a>
					<a href="#" class="list-group-item"><span class="badge">14</span> Active item</a>	
					<a href="#" class="list-group-item"><span class="badge">3</span> Second item</a>
					<a href="#" class="list-group-item"><span class="badge">25</span> Third item</a> 
					<a href="#" class="list-group-item"><span class="badge">14</span> Active item</a>
					<a href="#" class="list-group-item"><span class="badge">3</span> Second item</a>

					<div id="categories" class="collapse">

						<a href="#" class="list-group-item"><span class="badge">14</span> Active item</a>
						<a href="#" class="list-group-item"><span class="badge">3</span> Second item</a>
						<a href="#" class="list-group-item"><span class="badge">25</span> Third item</a> 
						<a href="#" class="list-group-item"><span class="badge">14</span> Active item</a>
						<a href="#" class="list-group-item"><span class="badge">3</span> Second item</a>
					</div>
					<button class="btn btn-default btn-sm btn-block" data-toggle="collapse" data-target="#categories">More <span class="caret"></span></button>
					<hr class="">
					<h4 class="">Viewing Options</h4>
					<a href="#" class="list-group-item"><span class="badge">14</span> Upcoming Sessions</a>

					<a href="#" class="list-group-item"><span class="badge">3</span> OnDemand</a>
					<hr class="">	
					<a href="#" class="list-group-item">Archived Courses</a>
					<a href="#" class="list-group-item">Courses In Development</a>
				</div>
			</div>
			<div class="hidden-sm hidden-xs">
				
				<hr>
				<div class="well">
					<h4>Premium Membership</h4>
					<p>Gain unlimited access to our entire course library.</p>
					<button class="btn btn-sm btn-warning">Learn more</button>

					<hr>
					<p class="text-center ">Already a member? <a href="#">Sign in.</a></p>
				</div> 

				<hr>

				<div class="well">
					<h4>Trusted Printer of Choice</h4>
					<p><a href="#"><img src="http://blog.unlessyouwill.com/wp-content/uploads/2012/09/tumblr_m3avvrbv3M1r146zvo1_500-400x500.jpg" class="img-responsive"></a></p>
					<p>Superior quality printing and great customer service are just some of the reasons why businesses, graphic designers and everyday consumers trust us with their printing - all backed by our 100% Quality Guarantee!</p>
					<button class="btn btn-sm btn-block btn-warning">Download</button>
				</div>

				<hr>
				<h4 class="text-center">CPE Partners</h4>
				<p><a href="#"><img class="center-block" src="http://placehold.it/100X100"></a></p>
			</div>
		</div>

	    <div class="col-md-9">  
	      	<div class="well hidden-xs"> 
				<div class="row">
					<div class="col-xs-4">
						<select class="form-control" id="sort_by">
							<option value="1">Sort By</option>
							<option value="datetime_posted desc">Recently Added</option>
							<option value="rating desc">Highest to Lowest Rating</option>
							<option value="rating asc">Lowest to Highest Rating</option>
						</select>
					</div>
					<div class="col-xs-8">
						<div class="btn-group pull-right">
						<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-th"></span></button>
						<button type="button" class="btn btn-default active"><span class="glyphicon glyphicon-th-list"></span></button>
						<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-list"></span></button>
						</div>
					</div>

				</div>
	      	</div>
	      
	     	 <hr>	
