<?php

$title = 'Sign Up';
$this->headTitle($title);
?>
<div class='signup-container'>
<?php if (!empty($errors)): ?>
	<div class="alert-danger col-sm-12 error-container" id="error">
		<?php foreach ($errors as $error) :?>
			<div class=" error-message"><strong>!</strong>&nbsp;&nbsp;<?php  echo $error?></div>
		<?php endforeach;?> 
	</div>
<?php endif; ?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
	<?php
		$form->setAttribute('action', $this->url('user', array('action' => 'signup')));

		$form->prepare();

		echo $this->form()->openTag($form);
		echo "<div class='form-group'>";
		echo $this->formRow($form->get('first_name')->setAttributes(array('class' => 'form-control col-sm-12')));
		echo "</div>";

		echo "<div class='form-group'>";
		echo $this->formRow($form->get('last_name')->setAttributes(array('class' => 'form-control col-sm-12')));
		echo "</div>";

		echo "<div class='form-group'>";
		echo $this->formRow($form->get('email')->setAttributes(array('class' => 'form-control col-sm-12')));
		echo "</div>";

		echo "<div class='form-group'>";
		echo $this->formRow($form->get('company_name')->setAttributes(array('class' => 'form-control col-sm-12')));
		echo "</div>";

		echo "<div class='form-group'>";
		echo $this->formRow($form->get('phone')->setAttributes(array('class' => 'form-control col-sm-5 numeric')));
		echo "</div>";
		echo "<div class='form-group'>";
		echo $this->formRow($form->get('password')->setAttributes(array('class' => 'form-control col-sm-12')));
		echo "</div>";
		echo "<div class='form-group'>";
		echo $this->formRow($form->get('confirm_password')->setAttributes(array('class' => 'form-control col-sm-12')));
		echo "</div>";
		echo $this->formSubmit($form->get('submit')->setAttributes(array('class' => 'btn btn-success')));

		echo $this->form()->closeTag();
	?>
</div>

