<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Exam'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/app/script.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse nav-custom">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('product'); ?>"><img src="<?php echo $this->basePath().'/images/uprinting.png'; ?>" id="image_male" class="img-responsive uprinting-logo"></a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                </ul>
                <ul id="log_button" class="nav navbar-nav navbar-right">
                        <li><a href="<?php echo $this->url('cart'); ?>"><span class="cart-count"><?php if(!empty($this->layout()->count))echo $this->layout()->count; else echo '0'; ?></span><img src="<?php echo $this->basePath().'/images/cart.png';?>" alt="cart" height="30" width="30"></a></li>
                    <?php if (empty($this->layout()->user_id)): ?>  
                        <li><a href="<?php echo $this->url('user', array('action' => 'login'));?>" id='login' class="popup log-button" ><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <?php else: ?> 
                        <li><label class="logged-name">Logged in as <?php echo $this->layout()->user_name; ?></label></li> 
                        <li><a href="<?php echo $this->url('user', array('action' => 'logout')); ?>" id="logout" class="log-button" onclick="return confirm('Are you sure you want to log out??')"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                    <?php endif ?> 
                </ul>
                </div>
            </div>
        </nav>

        <div class="container container-custom">
            <?php  echo $this->content; ?>
            <hr>
        </div> <!-- /container -->

         <footer>
            <div class="container">
                <p>&copy; 2005 - <?php echo date('Y') ?> by Rayman Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
