<div id="popup" class="modal fade" role="dialog">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
         <div class="modal-header">
         	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h3 class="modal-title" id="myModalLabel"> 
               Description <!-- contractor edit -->
            </h3>
         </div>
         <div class="modal-body row">
            <?php echo $this->content; ?>
            <input type="button" class="btn btn-default" data-dismiss="modal" value="Close">
         </div><!-- /.modal-content -->
    </div>
  </div>
</div>