<?php if (isset($cart_items)): ?>
	<table class="table table-hover" border='0'>
		<thead>
			<tr>
				<th width="20%">Product</th>
				<th width="20%"></th>
				<th><center>Quantity</center></th>
				<th>Price</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<?php 
				$price = 0; 
				foreach ($cart_items as $cart): ?>	
				<?php $price+=$cart['total_price']; ?>
				<tr>
					<td>
						<?php $path = explode("/",$cart['product_image'],4); ?>
						<div class="">
							<img src="<?php echo $this->basePath().'/'.$path[3]; ?>" id="image_male" class="img-responsive">
						</div>
					</td>
					<td align="center">
						<p><?php echo $cart['product_name']; ?></p>
						<p class="text-muted"><?php echo $cart['product_desc']; ?></p>
						<p><?php echo $cart['unit_price']; ?></p>
					</td>
					<td align="center"><?php echo $cart['qty']; ?></td>
					<td><?php echo $cart['total_price'] ;?></td>
					<td><a href="#">Edit</a>&nbsp;<a href="<?php echo $this->url('cart', array('action' => 'deleteByItem', 'id' => $cart["cart_item_id"])) ?>">Remove</a></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<table class="table table-total">
		<tr>
			<td colspan="4" align="right" style="border: none;">Subtotal :</td>
			<td align="right" style="border: none;">$ <?php echo number_format($price,2); ?></td>
		</tr>
		<tr>
			<td colspan="4" align="right" style="border: none;">Shipping :</td>
			<td align="right" style="border: none;">0</td>
		</tr>
		<tr>
			<td colspan="4" align="right" style="border: none;">Grand Total :</td>
			<td align="right" style="border: none;">$ <?php echo number_format($price,2); ?></td>
		</tr>
		<tr>
			<td colspan="5" align="right" style="border: none;"><a href="<?php echo (!empty($this->layout()->user_id) ? $this->url('shipping', array('action' => 'info')) : $this->url('user', array('action' => 'login')));?>" class="btn btn-success">Checkout</a></td>
		</tr>
	</table>	
<?php else:  ?>
<h3>Empty Cart</h3>
<?php endif; ?>
